---
- name: Install hashicorp binaries
  include_role:
    name: common
    tasks_from: apt.yaml
    apply:
      tags:
        - apt_install
  vars:
    binaries: "{{ hashicorp_binaries }}"
    handler_list: []