---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
  - apt_update

- name: Install binaries
  apt: 
    pkg: "{{ item }}"
    state: latest
  loop: "{{  binaries }}"
  notify: "{{ handler_list }}"
  tags:
  - apt_install